### PR TITLE
Added Crunch Compression Support

### PR DESCRIPTION
**Pull request by nikolayh**

### CODE REVIEW

**Comment by ivanpopelyshev** [comment]
Thank you for contribution!

Can you please convert those png's so I'll be able to test them? 

https://github.com/pixijs/examples/tree/gh-pages/required/assets/compressed

**Comment by nikolayh** [comment]
Done.
[crunch_compression.zip](https://github.com/pixijs/pixi-compressed-textures/files/813351/crunch_compression.zip)

**Comment by nikolayh** [comment]
Any update? @ivanpopelyshev

**Comment by ivanpopelyshev** [comment]
I was a bit busy. Gonna look at it in hour or two. I know you didn't care about lints, so I merge it and fix them later. I hate lints :)

**Comment by ivanpopelyshev** [comment]
It doesn't work for me. I modified the example in pixi-examples to use ".crn" instead of ".dds"

```
WebGL: INVALID_ENUM: compressedTexImage2D: invalid format
```

Ideas? Can you post an example that works? Even if its just zip-archive with html+js+crn

```js
var app = new PIXI.Application(800, 600, { resolution: window.devicePixelRatio || 1 });
app.view.style.width = "800px";
app.view.style.height = "600px";
document.body.appendChild(app.view);

// use empty array if you dont want to use detect feature
var extensions = ["@1x.crn", "@1x.png", "@1x.json", "@1x.atlas", ".crn"]

var loader = new PIXI.loaders.Loader();
loader.pre(PIXI.compressedTextures.extensionChooser(extensions));
// use @2x texture if resolution is 2, use dds format if its windows
var textureOptions1 = { metadata: {choice: ["@2x.png", ".crn", "@2x.crn"]} };
// use dds format if its windows but dont care for retina
var textureOptions2 = { metadata: {choice: [".crn"]} };
// while loading atlas, choose resolution for atlas and choose format for image
var atlasOptions = { metadata: { choice: ["@2x.json", "@1x.json"], imageMetadata: { choice: [".crn"]} } };

loader.add('building1', 'required/assets/compressed/building1.png', textureOptions1)
    .add('building2', 'required/assets/compressed/building2.png', textureOptions2)
    .add('atlas1', 'required/assets/compressed/buildings.json', atlasOptions )
    .load(function(loader, resources) {
        var spr1 = new PIXI.Sprite(resources.building1.texture);
        var spr2 = new PIXI.Sprite(resources.building2.texture);
        var spr3 = new PIXI.Sprite.fromImage('goldmine_10_5.png');
        var spr4 = new PIXI.Sprite.fromImage('wind_extractor_10.png');
        spr1.y = spr3.y = 150;
        spr2.y = spr4.y = 350;
        spr1.x = spr2.x = 250;
        spr3.x = spr4.x = 450;
        app.stage.addChild(spr1, spr2, spr3, spr4);
    });

// ATTENTION: PIXI recognizes resolution of atlas by suffix (@1x, @2x, ... )
// If you dont specify that, resolution of the atlas will be taken from "meta.scale"
// which in our example is 1 and 0.5 instead of 2 and 1. It will shrink everything!
```

**Comment by nikolayh** [comment]
@ivanpopelyshev, I have no issue when I test it.
Try this example
[pixi.zip](https://github.com/pixijs/pixi-compressed-textures/files/833247/pixi.zip)

**Comment by ivanpopelyshev** [comment]
change Line 7 to that thing:

```
var detectedExtensions = PIXI.compressedTextures.detectExtensions(app.renderer);
var extensions = [".crn"]
for (var i=0;i<detectedExtensions.length;i++) extensions.push(detectedExtensions[i])
```

that's what I get:

```
Uncaught ReferenceError: Module is not defined
    at CompressedImage._loadCRN (pixi-compressed-textures.js:548)
```

also you didn't include "json" files in achive, but that doesnt matter.

===============

OK, lets make it easier: 

```
var app = new PIXI.Application(800, 600, { resolution: window.devicePixelRatio || 1 });
document.body.appendChild(app.view);

var loader = new PIXI.loaders.Loader();
loader.pre(PIXI.compressedTextures.imageParser());
loader.add('building1', 'textures/building1.crn')
    .load(function(loader, resources) {
        var spr1 = new PIXI.Sprite(resources.building1.texture);
        spr1.y = 150;
        spr1.x = 250;
        app.stage.addChild(spr1);
    });
```

that thing fails. With a file in archive it cant find "Module", but even if I rebuild the plugin, i have that webgl error.

Now we have something to debug :)

**Comment by andrewstart** [comment]
@nikolayh how do you generate your .crn files?

**Comment by ivanpopelyshev** [comment]
We have a problem since 4.3.5: https://github.com/pixijs/pixi-compressed-textures/pull/9

I think its related

**Comment by nikolayh** [comment]
@andrewstart, you need to download crunch library (https://github.com/BinomialLLC/crunch)
After that go to bin directory and execute this command
` ../crunch_x64.exe -file file.png -q 255 -alphaThreshold 255 -dxtQuality uber -DXT5 -mipMode None`

@ivanpopelyshev, Module should be global variable which reference to crunch library (crn_decomp.js).
crn_decomp.js should have this line
`window.Module = Module` 
or if is uglyfy
`window.Module = e`
This is how this library works.

Beside that when I open index.html from the zip that I sent you - everything works great without any issue.

> We have a problem since 4.3.5: #9

I think is not related.

**Comment by nikolayh** [comment]
Try this
[pixi.zip](https://github.com/pixijs/pixi-compressed-textures/files/837484/pixi.zip)

Which browser and version you use? (maybe its browser thing?)

**Comment by nikolayh** [comment]
@ivanpopelyshev ?:)

**Comment by ivanpopelyshev** [comment]
I found error in pixi-compressed, so we are ready to merge!

**Comment by ivanpopelyshev** [comment]
We just had to detect extensions on initContext

**Pull request merged**
